language: R
cache: packages
r_packages:
  - devtools
  - covr
  - roxygen2
  - foreach
  - survival
  - parallel
  - foreach
  - doParallel
  - dynamicTreeCut
  - grDevices
  - matrixStats
  - Hmisc
  - impute
  - splines
  - preprocessCore
bioc_packages:
  - GO.db
  - AnnotationDbi
sudo: false
before_script:
  - Rscript -e 'library(tools); md5sum(list.files(recursive = TRUE))'
#  - Rscript -e 'library(devtools); document()'
after_success:
  - Rscript -e 'library(covr); codecov()'
os:
- linux
r:
- bioc-release
notifications:
  email:
    on_success: change
    on_failure: change
