language: R

cache: packages
r_packages:
  - covr
  - roxygen2
sudo: required
before_script:
  - Rscript -e 'library(devtools); document()'

after_success:
  - Rscript -e 'library(covr); codecov()'

os:
- linux

r:
- bioc-release
