library("WGCNA")
context("Testing corAndPvalue")

test_that("corAndPvalue", {
    x <- c(0.2, 0.3, 0.5)
    y <- c(0.3, 0.2, 0.5)
    test <- corAndPvalue(x, y)
    expect_length(test, 5L)
    test1 <- corAndPvalue(x, y, alternative = "greater")
    expect_length(test1, 5L)
    test2 <- corAndPvalue(x, y, alternative = "less")
    expect_length(test2, 5L)
    test3 <- corAndPvalue(x, y, alternative = "two.sided")
    expect_length(test3, 5L)
    test4 <- corAndPvalue(x)
    expect_length(test4, 5L)
    x <- matrix(rnorm(10), 2)
    y <- matrix(rnorm(10), 2)
    test5 <- corAndPvalue(x, y)
    expect_equal(ncol(test5$cor), 5L)
    expect_equal(nrow(test5$cor), 5L)
})


test_that("bicorAndPvalue", {
    x <- c(0.2, 0.3, 0.5)
    y <- c(0.3, 0.2, 0.5)
    test <- bicorAndPvalue(x, y)
    expect_length(test, 5L)
    test1 <- bicorAndPvalue(x, y, alternative = "greater")
    expect_length(test1, 5L)
    test2 <- bicorAndPvalue(x, y, alternative = "less")
    expect_length(test2, 5L)
    test3 <- bicorAndPvalue(x, y, alternative = "two.sided")
    expect_length(test3, 5L)
    test4 <- bicorAndPvalue(x)
    expect_length(test4, 5L)
    x <- matrix(rnorm(10), 2)
    y <- matrix(rnorm(10), 2)
    test5 <- bicorAndPvalue(x)
    expect_warning(bicorAndPvalue(x, y))
    expect_equal(ncol(test5$bicor), 5L)
    expect_equal(nrow(test5$bicor), 5L)
})
